### ISSUE TITLE
Security Issue by returning Hashed Password

### ISSUE THREAD

**Issue by TyrantGummiBear** [ChasVanDav/budgetblog#1]
This line is extremely dangerous, returning the hashed password to the user would allow the user to attempt to brutce force the local encryption keys due to having the hashed password and knowing their own password. Depending on what is necessary for the site to receive it would be better to return simply a success or possibly the username.

'INSERT INTO users (username, email, password, home_country, home_city, home_currency) VALUES ($1, $2, $3, $4, $5, $6) RETURNING *',

https://github.com/ChasVanDav/budgetblog/blob/e9e2ce722e74c7bfd2ab4ab9766af9eecc95c178/backend/controllers/userController.js#L14

**Comment by ChasVanDav** [comment]
@Freedark what does it mean to brute force local encryption keys?
@Xhz0729 did you run into this issue as well?

**Comment by Xhz0729** [comment]
@ChasVanDav This's a good point! I found this blog about [brute force attack](https://www.splunk.com/en_us/blog/learn/brute-force-attacks.html#:~:text=Definition%20and%20Methods%3A%20Brute%20force,systematically%20trying%20all%20possible%20combinations.)
Returning the entire user record, including the hashed password, in the response is a security risk. Even though the password is hashed, exposing it could still give malicious actors information they could use to attempt a brute force attack.
I would suggest change the code to insert all fields but not return the hashed password.

**Comment by ChasVanDav** [comment]
@Xhz0729 Thank you for helping to elucidate this issue! You're so good at explaining tough concepts and breaking it down. I shall re-write that line of code to exclude the hashed password. @Freedark Thank you for bringing this issue to light! I shall update it asap!

**Comment by ChasVanDav** [comment]
I have removed the section of code returning the hashed password. With this I close the issue.
